### ISSUE TITLE
download link broken

### ISSUE THREAD

**Issue by GabrielF00** [whym/wikihadoop#10]
Hi,

I'm just starting to experiment with this project. However, I noticed that the link on the download page to wikihadoop-0.2.jar is broken. I'm going to attempt to build myself.

Best,
Gabriel

**Comment by drdee** [comment]
Which link are you referring to?

**Comment by GabrielF00** [comment]
On the download page:
https://github.com/whym/wikihadoop/downloads

Link #1 - wikihadoop-0.2.jar — Compiled WikiHadoop 0.2 for Apache Hadoop 0.21, 0.22 and 0.23

I was able to build the project myself but it would be nice to have a functional jar file to download because the instructions say that it's available.

Thanks

**Comment by whym** [comment]
It looks like GitHub does not support this kind of downloadable files anymore [1].  Since the official 90-days transition period has been already over, I'm not sure how long the other remaining jars to be available here.

Diederik, if this is of interest to users and to you, could you find somewhere to host the package?  The file in question was just a result of "mvn package".

[1] https://github.com/blog/1302-goodbye-uploads

**Comment by ravisg** [comment]
@dvanliere - Hello Diederik , I am an Information Science grad student and I would like to use your wikihadoop code. My goal is to compare the pages in Wikipedia against Ontology sets and find out the pages which have matching words from the set. 
   I am  a beginner in Hadoop but I am proficient in Java . Can I get any documentation for your code , so that I can use it further to do word matches against my vocabulary (ontology) sets. Any help/suggestions will be greatly appreciated

**Comment by whym** [comment]
I have set up a (very minimalistic) download page and revised the doc in the above commit - this should work for now.
